apiVersion: apps/v1
kind: Deployment
metadata:
#Name should notbe more than 13 letters
  name: ibps5sp3uiweb
  labels:
    tags.datadoghq.com/env: UAT
    tags.datadoghq.com/service: ibps5sp3uiweb
    tags.datadoghq.com/version: v1
spec:
  replicas: 1
  selector:
      matchLabels:
        name: ibps5sp3uiweb
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ibps5sp3uiweb
        tags.datadoghq.com/env: UAT
        tags.datadoghq.com/service: ibps5sp3uiweb
        tags.datadoghq.com/version: v1
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/config.mode: "socket"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.11.2     
    spec:
      containers:
      - name: ibps5sp3uiweb
        image: docker.cldgit.hdfc.com/hdfcltd/clos_userinstance/hdfc_ibps5userinstanceweb:sp3-sit-alpha-3.1.0
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: 4096Mi
            cpu: 1800m
          limits:
            memory: 4096Mi
            cpu: 1800m
        volumeMounts:        
        - name: ng-config
          mountPath: /Newgen/jws-5.7/tomcat/bin/Newgen/NGConfig
        - name: ng-temp
          mountPath: /Newgen/jws-5.7/tomcat/bin/Newgen/NGTemp
        - name: jws-context-xml
          mountPath: /Newgen/jws-5.7/tomcat/conf/context.xml
        - name: jws-server-xml
          mountPath: /Newgen/jws-5.7/tomcat/conf/server.xml  
        - name: jws-web-xml
          mountPath: /Newgen/jws-5.7/tomcat/conf/web.xml  
        - name: ngcache
          mountPath: /Newgen/jws-5.7/tomcat/bin/Newgen/NGCache
        - name: clos-ini
          mountPath: /Newgen/jws-5.7/tomcat/bin/Clos_INI          
        - name: disbursement-ini
          mountPath: /Newgen/jws-5.7/tomcat/bin/Disbursement_INI 
        - name: monitoring-ini
          mountPath: /Newgen/jws-5.7/tomcat/bin/Monitoring_INI          
        - name: noc-ini
          mountPath: /Newgen/jws-5.7/tomcat/bin/NOC_INI          
        - name: templategeneration
          mountPath: /Newgen/jws-5.7/tomcat/bin/TemplateGeneration
        - name: kendoclos
          mountPath: /Newgen/jws-5.7/tomcat/bin/KendoCLOS
        - name: tomcat-logs
          mountPath: /Newgen/jws-5.7/tomcat/logs
          subPathExpr: $(POD_NAME)
        - name: nglogs
          mountPath: /Newgen/jws-5.7/tomcat/bin/Newgen/NGLogs
          subPathExpr: $(POD_NAME)
        ports:
         - name: http
           containerPort: 8080
        readinessProbe:
          httpGet:
            path: /omniapp
            port: 8080
          # Intial delay is set to a high value to have a better
          # visibility of the ramped deployment
          initialDelaySeconds: 30
          periodSeconds: 5
       # livenessProbe:
        #  httpGet:
         #   path: /omniapp
          #  port: 8080
         # initialDelaySeconds: 300
         # failureThreshold: 5
         # periodSeconds: 10
        env:
          - name: Release_Pipeline_Number
            value: "AWS-Release-Build_Pipeline_Number"
          - name: JAVA_OPTS
            value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+DisableExplicitGC -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=50.0"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "false"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      imagePullSecrets:
        - name: docker
      volumes:
        - name: ng-config
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/NGConfig
            type: DirectoryOrCreate
        - name: ng-temp
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/NGTemp
            type: DirectoryOrCreate
        - name: jws-context-xml
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/context.xml
            type: File
        - name: jws-server-xml
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/server.xml
            type: File    
        - name: jws-web-xml
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/web.xml
            type: File
        - name: tomcat-logs
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/ProductLogs/UserInstance/ibps5sp3uiweb-AWS-Release-Build_Pipeline_Number/tomcat_logs
            type: DirectoryOrCreate
        - name: nglogs
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/ProductLogs/UserInstance/ibps5sp3uiweb-AWS-Release-Build_Pipeline_Number/NGLogs
            type: DirectoryOrCreate
        - name: ngcache
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/NGCache
            type: DirectoryOrCreate
        - name: clos-ini
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/Clos_INI
            type: DirectoryOrCreate
        - name: disbursement-ini
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/Disbursement_INI
            type: DirectoryOrCreate
        - name: monitoring-ini
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/Monitoring_INI
            type: DirectoryOrCreate
        - name: noc-ini
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/NOC_INI
            type: DirectoryOrCreate
        - name: templategeneration
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/TemplateGeneration
            type: DirectoryOrCreate
        - name: kendoclos
          hostPath:
            path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/WEB/KendoCLOS
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: ibps5sp3uiweb
  namespace: default
spec: 
  selector:
   name: ibps5sp3uiweb
  ports:
   - name: http
     port: 8080
     targetPort: 8080
# For Expose
  type: NodePort
  
---  
  
apiVersion: apps/v1
kind: Deployment
metadata:
#Name should not be more than 13 letters
  name: ibps5sp3uiejb
spec:
  replicas: 1
  selector:
      matchLabels:
        name: ibps5sp3uiejb
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ibps5sp3uiejb
        tags.datadoghq.com/env: UAT
        tags.datadoghq.com/service: ibps5sp3uiejb
        tags.datadoghq.com/version: v1
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/config.mode: "socket"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.11.2
    spec:
      containers:
      - name: ibps5sp3uiejb
        image: docker.cldgit.hdfc.com/hdfcltd/clos_userinstance/hdfc_ibps5userinstanceejb:sp3-sit-alpha-3.1.0
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: 4096Mi
            cpu: 1000m
          limits:
            memory: 4096Mi
            cpu: 1000m
        volumeMounts:
        - name: ngdbini
          mountPath: /Newgen/jboss-eap-7.4/bin/Newgen/NGConfig/ngdbini
        - name: ibpsconfig
          mountPath: /Newgen/jboss-eap-7.4/bin/Newgen/NGConfig/omniflowconfiguration
        - name: ngtemp
          mountPath: /Newgen/jboss-eap-7.4/bin/Newgen/NGTemp
        - name: configuration
          mountPath: /Newgen/jboss-eap-7.4/standalone/configuration
        - name: server-logs
          mountPath: /Newgen/jboss-eap-7.4/standalone/log
          subPathExpr: $(POD_NAME)
        - name: nglogs
          mountPath: /Newgen/jboss-eap-7.4/bin/Newgen/NGLogs
          subPathExpr: $(POD_NAME)
        - name: integrationadapterlogs
          mountPath: /Newgen/jboss-eap-7.4/bin/IntegrationAdapterLogs
          subPathExpr: $(POD_NAME)
        - name: integrationadapter-config
          mountPath: /Newgen/jboss-eap-7.4/bin/IntegrationAdapter_Config
        ports:
         - name: http
           containerPort: 8080
         - name: http1
           containerPort: 9990
        readinessProbe:
          exec:
            command:
            - cat
            - /Newgen/jboss-eap-7.4/standalone/deployments/wfs_ejb.jar.deployed
          # Intial delay is set to a high value to have a better
          initialDelaySeconds: 30
          periodSeconds: 5
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 8080
        # initialDelaySeconds: 300
        #  failureThreshold: 5
        #  periodSeconds: 10
        env:
          - name: Release_Pipeline_Number
            value: "AWS-Release-Build_Pipeline_Number"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "false"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      imagePullSecrets:
        - name: docker
      volumes:
      - name: ngdbini
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/EJB/NGConfig/ngdbini
      - name: ibpsconfig
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/EJB/NGConfig/omniflowconfiguration
      - name: ngtemp
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/EJB/NGTemp
      - name: configuration
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/EJB/configuration
      - name: server-logs
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/ProductLogs/UserInstance/ibps5sp3uiejb-AWS-Release-Build_Pipeline_Number/Server_Logs
          type: DirectoryOrCreate
      - name: nglogs
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/ProductLogs/UserInstance/ibps5sp3uiejb-AWS-Release-Build_Pipeline_Number/NGLogs
          type: DirectoryOrCreate
      - name: integrationadapterlogs
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/ProductLogs/UserInstance/ibps5sp3uiejb-AWS-Release-Build_Pipeline_Number/IntegrationAdapterLogs
          type: DirectoryOrCreate
      - name: integrationadapter-config
        hostPath:
          path: /mount/efs/iBPS5.0SP3/ConfigurationFiles/iBPS5.0SP3/UserInstance/EJB/IntegrationAdapter_Config
          type: DirectoryOrCreate   
---
apiVersion: v1
kind: Service
metadata:
  name: ibps5sp3uiejb
  namespace: default
spec: 
  selector:
   name: ibps5sp3uiejb
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http1
    port: 9990
    protocol: TCP
    targetPort: 9990
# For Expose
  type: NodePort
